export const cn = (...classes: Array<string | false | null | undefined>) =>
  classes.filter(Boolean).join(" ");

export const formatYear = (year: number) => String(year);

export const flagForCountry = (countryCode: string) => {
  const flags: Record<string, string> = {
    AGO: "🇦🇴",
    ARE: "🇦🇪",
    ARG: "🇦🇷",
    ALG: "🇩🇿",
    AUT: "🇦🇹",
    AUS: "🇦🇺",
    BEL: "🇧🇪",
    BGR: "🇧🇬",
    BIH: "🇧🇦",
    BOL: "🇧🇴",
    BRA: "🇧🇷",
    CAN: "🇨🇦",
    CHE: "🇨🇭",
    CHI: "🇨🇱",
    CHL: "🇨🇱",
    CHN: "🇨🇳",
    CIV: "🇨🇮",
    CMR: "🇨🇲",
    COL: "🇨🇴",
    CRC: "🇨🇷",
    CRI: "🇨🇷",
    CRO: "🇭🇷",
    HRV: "🇭🇷",
    CPV: "🇨🇻",
    CUW: "🇨🇼",
    CZE: "🇨🇿",
    COD: "🇨🇩",
    DZA: "🇩🇿",
    DEN: "🇩🇰",
    DNK: "🇩🇰",
    ENG: "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    ECU: "🇪🇨",
    EGY: "🇪🇬",
    ESP: "🇪🇸",
    FRA: "🇫🇷",
    GER: "🇩🇪",
    DEU: "🇩🇪",
    GHA: "🇬🇭",
    GRC: "🇬🇷",
    HAI: "🇭🇹",
    HTI: "🇭🇹",
    HND: "🇭🇳",
    HUN: "🇭🇺",
    IRL: "🇮🇪",
    IRQ: "🇮🇶",
    ISL: "🇮🇸",
    ISR: "🇮🇱",
    ITA: "🇮🇹",
    IRN: "🇮🇷",
    JPN: "🇯🇵",
    JAM: "🇯🇲",
    JOR: "🇯🇴",
    KOR: "🇰🇷",
    PRK: "🇰🇵",
    KWT: "🇰🇼",
    MAR: "🇲🇦",
    MEX: "🇲🇽",
    NED: "🇳🇱",
    NLD: "🇳🇱",
    NGA: "🇳🇬",
    NOR: "🇳🇴",
    NZL: "🇳🇿",
    PAN: "🇵🇦",
    PAR: "🇵🇾",
    POR: "🇵🇹",
    PRT: "🇵🇹",
    PER: "🇵🇪",
    PRY: "🇵🇾",
    POL: "🇵🇱",
    ROU: "🇷🇴",
    RSA: "🇿🇦",
    ZAF: "🇿🇦",
    RUS: "🇷🇺",
    KSA: "🇸🇦",
    SAU: "🇸🇦",
    SEN: "🇸🇳",
    SRB: "🇷🇸",
    SUI: "🇨🇭",
    SVK: "🇸🇰",
    SVN: "🇸🇮",
    SWE: "🇸🇪",
    TUN: "🇹🇳",
    TGO: "🇹🇬",
    TTO: "🇹🇹",
    TUR: "🇹🇷",
    UKR: "🇺🇦",
    USA: "🇺🇸",
    URU: "🇺🇾",
    URY: "🇺🇾",
    UZB: "🇺🇿",
    QAT: "🇶🇦",
    SLV: "🇸🇻",
    SCO: "🏴",
    WAL: "🏴",
    CSK: "◇",
    DDR: "◇",
    NIR: "◇",
    SCG: "◇",
    SUN: "◇",
    YUG: "◇",
    TXI: "✦",
    ALL: "✦",
  };
  return flags[countryCode] ?? "◌";
};

export const flagForTeamName = (countryName: string) => {
  const codes: Record<string, string> = {
    Argentina: "ARG",
    Brazil: "BRA",
    Croatia: "CRO",
    France: "FRA",
    Germany: "GER",
    Italy: "ITA",
    Morocco: "MAR",
    Netherlands: "NED",
    Portugal: "POR",
    "Saudi Arabia": "KSA",
    Senegal: "SEN",
    "South Korea": "KOR",
    Spain: "ESP",
    Uruguay: "URU",
  };
  return flagForCountry(codes[countryName] ?? "");
};
